Table sal_emp {
  name text
  pay_by_quarter "int[]" [not null]
  schedule "text[][]" [null]
  unquoted text[] [not null]
  mixed "character varying"[]
}

Table tictactoe {
  squares "integer[3][3]"
}
